---
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: "****"
  AWS_SECRET_ACCESS_KEY: "****"
  AWS_DEFAULT_REGION: eu-west-1
kind: ConfigMap
metadata:
  name: aws-secrets-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spinnaker-operator
  template:
    metadata:
      labels:
        name: spinnaker-operator
    spec:
      serviceAccountName: spinnaker-operator
      containers:
        - name: spinnaker-operator
          image: armory/spinnaker-operator:dev # Moving label, replaced at build time with a fixed version in "build" dir
          command:
            - spinnaker-operator
          args:
            - --disable-admission-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "spinnaker-operator"
          envFrom:
            - configMapRef:
                name: aws-secrets-map       
        - name: halyard
          image: armory/halyard:operator-dev # Moving label, replaced at build time with a fixed version in "build" dir
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: aws-secrets-map
          ports:
            - containerPort: 8064
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8064
            failureThreshold: 20
            periodSeconds: 5
            initialDelaySeconds: 20
          livenessProbe:
            tcpSocket:
              port: 8064
            initialDelaySeconds: 30
            periodSeconds: 20
